AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bytewise SAM Template


Resources:

  BytwiseHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: default
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"

  BytewiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bytewise.handler
      CodeUri: resources/bytewise
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Ref DependenciesLayer
      Events:
        BytewiseEvent:
          Type: HttpApi
          Properties:
            Path: /bytewise/{id}
            Method: GET
            ApiId: !Ref BytwiseHttpApi

  BytewiseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bytewise-queue.fifo
      FifoQueue: true



  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/common
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7





